### PR TITLE
Make and include poll for Culture of Concentration.

### PR DESCRIPTION
**Pull request by whilei**
:bar_chart:

### CODE REVIEW

**Comment by whilei** [comment]
__What does concentration look like for you?__

https://goo.gl/forms/Td2CKC2Xfpp5g1q13 

Google Sheet: https://docs.google.com/spreadsheets/d/1HhE2PKJsp0268IR5Sg41Dbxcv3BCZ_cYoccfNXZ4mIQ/edit?usp=sharing

**Comment by webappzero** [comment]
Awesome!

**Comment by webappzero** [comment]
Can you add me as a collaborator with full permissions to all the forms we make?

**Comment by whilei** [comment]
Ah, of course! ✅

**Pull request merged**
