### PR TITLE
Classroom hands-up image for Audience Participation slide.

### PR DESCRIPTION
**Pull request by whilei**

### CODE REVIEW

**Comment by webappzero** [comment]
You know its weird. Seeing that picture, I noticed that my mood shifted down a notch. Elementary school was a big adjustment for for me.

The environment felt very institutional versus the colorful world where I got to roam free in nature.

Also, the tabular like structure of the chairs, and staring at the back of someone's head.

I like the idea of moving from squares to circles for seating. How about we go with something like this?

https://upload.wikimedia.org/wikipedia/commons/7/7f/Djembes.jpg

**Comment by webappzero** [comment]
Great idea to have a picture here!

**Comment by whilei** [comment]
Yep - was wondering about that - swapping pronto.

**Comment by webappzero** [comment]
Great QR tie in!!!

**Pull request merged**
