### PR TITLE
Proofreading, commenting, editing...

### PR DESCRIPTION
**Pull request by whilei**
and improvising 😉 .

Changes include
- "how ~~much~~ do I value learning"
- removed some slides entirely
- use fullscreen video in lieu of another title slide
- comments on speaker's notes in some places
- notes for TODOs for myself w/r/t (with regard to) graphics

All changes up until but including or beyond _The Answer_ section.

(Addresses #51)

### CODE REVIEW

**Comment by webappzero** [comment]
Great stuff, Isaac!

**Comment by whilei** [comment]
Now includes fixes for merge conflicts since your last push; all resolved in your favor 😉 

Doesn't mean you have to pull, though! Can happily use it simply a source of reference.

**Comment by webappzero** [comment]
Looks like this has some merge conflicts, maybe I pulled in the wrong order.

**Comment by whilei** [comment]
I'll take a peek.  It was/is a fairly "impactful" and opinionated set of changes... will review and refine the changes locally and make another push to this PR.

**Comment by webappzero** [comment]
I've read through these commits and have already absorbed most of the good stuff. Little nervous about rewriting over the stuff I did yesterday. Everything up to answer is thoroughly written now.

**Comment by whilei** [comment]
Yep, yep, all good. The branch is always there, in any case 👍

**Pull request closed without merging**
