### PR TITLE
Fix illustrations montages and resize footinmouthjay.

### PR DESCRIPTION
**Pull request by whilei**

### CODE REVIEW

**Comment by webappzero** [comment]
These look great. Just curious. I noticed you created some extra sizes & layouts for some assets. Are you thinking ahead toward making the presentation responsive? Just curious.

**Comment by whilei** [comment]
Those were along-the-way test cases and alternatives, just in case. 

To that point though, I think it would worth thinking together out loud about priorities as far mobile responsiveness go too.

**Comment by webappzero** [comment]
Yes, this a good agenda item for a mini-meeting. Please book a fifteener with me at my calendly on the 45 min mark of any hour that's free tomorrow or after with label 'responsive' and we'll aim for 10 min mtg.

**Comment by whilei** [comment]
Shoot - I just book 3pm here - 8am there -- missed the 45min marker. Let's make it 3:45/8:45!

**Comment by whilei** [comment]
Or is it -6h? I think so. Makes it 9:45. Yep. 9:45 you, 3:45 me.  `responsive`

**Comment by webappzero** [comment]
No worries. You rebook through calendly of you like.

**Comment by whilei** [comment]
Got it. Till then!

**Comment by webappzero** [comment]
rough draft of 9 min meeting agenda
intro 3 min
body 3 min
conclusion 3 min

intro observe problem
body define solution candidates
conclusion select best fit candidate

initial thoughts:
observe:
- Time goal is fixed (feb 10), but this will live on & have our names on it.
- We might be able to harmonize our work with Reveal.js existing responsiveness. "go with the grain"

**Pull request merged**
